_unit = _unit select 0;

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add containers";
_unit forceAddUniform "BWA3_Uniform_Crew_Fleck";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_elasticBandage";};
_unit addItemToUniform "BW_Facepaint";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_epinephrine";};
_unit addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 3 do {_unit addItemToUniform "ACE_CableTie";};
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_Kestrel4500";
_unit addItemToUniform "ACE_EntrenchingTool";
_unit addItemToUniform "ACE_Flashlight_XL50";
_unit addItemToUniform "ACE_microDAGR";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_morphine";};
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_packingBandage";};
_unit addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 3 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addVest "VSM_LBT1961_GRN";
for "_i" from 1 to 6 do {_unit addItemToVest "BWA3_DM25";};
for "_i" from 1 to 2 do {_unit addItemToVest "BWA3_DM51A1";};
_unit addItemToVest "ACE_M14";
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_IR";};
for "_i" from 1 to 6 do {_unit addItemToVest "BWA3_DM32_Orange";};
_unit addBackpack "BWA3_TacticalPack_Fleck";
_unit addItemToBackpack "BWA3_CrewmanKSK_Fleck";
_unit addItemToBackpack "dsk_nsv";
for "_i" from 1 to 4 do {_unit addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 9 do {_unit addItemToBackpack "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_M84";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "ACE_Chemlight_HiOrange";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "Chemlight_green";};
for "_i" from 1 to 9 do {_unit addItemToBackpack "hlc_30Rnd_9x19_B_MP5";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "BWA3_15Rnd_9x19_P8";};
_unit addHeadgear "rhs_beanie_green";
_unit addGoggles "VSM_Facemask_black_Peltor_glasses";

comment "Add weapons";
_unit addWeapon "hlc_smg_MP5N";
_unit addWeapon "BWA3_P8";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "Itemwatch";
_unit linkItem "TFAR_anprc152";
_unit linkItem "ACE_GD300_b";